language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
env: LD_BIND_NOW=1
before_script:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - cmake .
  - make
script: ctest -V --timeout 120
