sudo: false
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
env:
  - LD_BIND_NOW=1
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
before_script:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - ls -la /usr/bin/gcc-* /usr/bin/g++* /usr/bin/clang*
  - ./cmake-3.2.3-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Release .
  - make
  - ulimit -c unlimited -S
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-5
    - g++-5
    - clang-3.7
    - gdb
script:
  - RESULT=0
  - make test
  - for i in core*; do b=$(file "$i" | sed "s/.*from '\([^']\+\)'.*/\1/"); gdb "$b" "$i" -ex "thread apply all bt" -ex "set pagination 0" -batch; done
  - if [[ ${RESULT} != 0 ]]; then exit $RESULT ; fi;
