sudo: false
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
env:
  - LD_BIND_NOW=1
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
before_script:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - ls -la /usr/bin/gcc-* /usr/bin/g++* /usr/bin/clang*
  - ./cmake-3.2.3-Linux-x86_64/bin/cmake .
  - make
  - ulimit -c unlimited -S
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-5
    - g++-5
    - clang-3.7
    - gdb
script:
  - RESULT=0
  - ctest -V --timeout 240
  - if [[ ${RESULT} == 0 ]]; then echo "\\o/ our test worked without problems"; else echo "ruhroh test returned an errorcode of $RESULT"; fi;
  # If the program returned an error code, now we check for a
  # core file in the current working directory and dump the backtrace out
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
  # now we should present travis with the original
  # error code so the run cleanly stops
  - if [[ ${RESULT} != 0 ]]; then exit $RESULT ; fi;
