language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
env: LD_BIND_NOW=1
before_script:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.2.3-Linux-x86_64/* /usr
  - cmake .
  - make
script: ctest -V --timeout 120
